nelmio_cors:

  defaults:

    allow_credentials: false
    allow_origin: [ ]
    allow_headers: [ ]
    allow_methods: [ ]
    expose_headers: [ ]
    max_age: 0
    hosts: [ ]
    origin_regex: false
    forced_allow_origin_value: ~


  paths:

    '^/': # ajusta el path según tus necesidades
      allow_origin: [ '*' ]
      allow_headers: [ '*' ]
      allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE' ]
      max_age: 3600

    '^/api/login_check':
      allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
      allow_headers: [ 'Content-Type' ]
      allow_methods: [ 'POST' ]
      max_age: 3600